
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


def show_frame_1():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"E:\MD\AA SLU\BSEcE\4th Yr '23 2nd Sem\Capstone\pill-identification\output\frame1\build\assets\frame0")

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path) 
    
    window = Tk()

    window.geometry("800x480")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 480,
        width = 800,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        400.0,
        249.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        400.0,
        242.0,
        image=image_image_2
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        400.0,
        230.0,
        image=image_image_3
    )

    canvas.create_text(
        276.0,
        374.0,
        anchor="nw",
        text="press the screen to start",
        fill="#9C9C9C",
        font=("InriaSans BoldItalic", 24 * -1)
    )
    window.resizable(False, False)
    window.mainloop()

def show_frame_2():

    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"E:\MD\AA SLU\BSEcE\4th Yr '23 2nd Sem\Capstone\pill-identification\output\frame2\build\assets\frame0")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    window = Tk()

    window.geometry("800x480")
    window.configure(bg = "#EDF5FA")


    canvas = Canvas(
        window,
        bg = "#EDF5FA",
        height = 480,
        width = 800,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        535.8487548828125,
        464.5844939194576,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        343.0,
        56.0,
        image=image_image_2
    )

    canvas.create_text(
        4.0,
        130.0,
        anchor="nw",
        text="Insert the pill into the designated pill slot, ensuring proper alignment.",
        fill="#000000",
        font=("Inter Medium", 60 * -1)
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        646.0,
        382.0,
        image=image_image_3
    )

    canvas.create_text(
        17.0,
        11.0,
        anchor="nw",
        text="23:01",
        fill="#DADADA",
        font=("InriaSans Bold", 40 * -1)
    )
    window.resizable(False, False)
    window.mainloop()

def show_frame_3():

    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"E:\MD\AA SLU\BSEcE\4th Yr '23 2nd Sem\Capstone\pill-identification\output\frame3\build\assets\frame0")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)



    window = Tk()

    window.geometry("800x480")
    window.configure(bg = "#EDF5FA")


    canvas = Canvas(
        window,
        bg = "#EDF5FA",
        height = 480,
        width = 800,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        455.9680175121721,
        314.84588623046875,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        613.0,
        47.0,
        image=image_image_2
    )

    canvas.create_text(
        167.0,
        84.0,
        anchor="nw",
        text=f"{pill_info[0]}",
        fill="#000000",
        font=("Inter Medium", 36 * -1)
    )

    canvas.create_text(
        293.0,
        171.0,
        anchor="nw",
        text="Dosage:\n%s\n\nSpecial Instruction:\n%s\n\nPossible side effects:\n%s" % (pill_info[1], pill_info[2], pill_info[3]),
        fill="#000000",
        font=("Inter Regular", 24 * -1)
    )

    canvas.create_rectangle(
        17.0,
        171.0,
        276.0,
        406.0,
        fill="#D9D9D9",
        outline="")

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        34.0,
        188.0,
        image=image_image_3
    )

    canvas.create_text(
        17.0,
        11.0,
        anchor="nw",
        text="23:01",
        fill="#DADADA",
        font=("InriaSans Bold", 40 * -1)
    )
    window.resizable(False, False)
    window.mainloop()

def show_frame_4():

    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"E:\MD\AA SLU\BSEcE\4th Yr '23 2nd Sem\Capstone\pill-identification\output\frame4\build\assets\frame0")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    window = Tk()

    window.geometry("800x480")
    window.configure(bg = "#EDF5FA")


    canvas = Canvas(
        window,
        bg = "#EDF5FA",
        height = 480,
        width = 800,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        411.6100484791996,
        168.53253173828125,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        613.0,
        47.0,
        image=image_image_2
    )

    canvas.create_text(
        167.0,
        84.0,
        anchor="nw",
        text="name ng gamot",
        fill="#000000",
        font=("Inter Medium", 36 * -1)
    )

    canvas.create_text(
        293.0,
        171.0,
        anchor="nw",
        text="Dosage:\n\nSpecial Instruction:\n\nPossible side effects:",
        fill="#000000",
        font=("Inter Regular", 24 * -1)
    )

    canvas.create_rectangle(
        17.0,
        171.0,
        276.0,
        406.0,
        fill="#D9D9D9",
        outline="")

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        34.0,
        188.0,
        image=image_image_3
    )

    canvas.create_text(
        17.0,
        11.0,
        anchor="nw",
        text="23:01",
        fill="#DADADA",
        font=("InriaSans Bold", 40 * -1)
    )

    canvas.create_text(
        162.0,
        426.0,
        anchor="nw",
        text="press the screen to identify new pill",
        fill="#9C9C9C",
        font=("InriaSans BoldItalic", 24 * -1)
    )
    window.resizable(False, False)
    window.mainloop()